TABLE_SCHEMAS = {
    "active_contract_list": ['id', 'vendor_name', 'contract_type', 'contract_end_date', 'payment_terms'],
    "active_contracts": ['customer_id', 'name', 'contract_id', 'start', 'end', 'value', 'status'],
    "approved_payments": ['request_id', 'paid_by', 'category', 'approved_amount', 'payment_mode', 'transaction_ref', 'payment_date', 'status'],
    "approved_summary": ['id', 'total_annual_cost', 'total_annual_price', 'overall_gross_margin', 'gm_with_doc', 'total_visits_per_month', 'approved_on'],
    "branch": ['branch', 'value'],
    "branch_contracts": ['branch', 'count'],
    "branch_customers": ['branch', 'count'],
    "branch_density": ['state', 'count'],
    "branch_directory": ['branch_name', 'branch_code', 'city', 'email', 'phone_number'],
    "branch_expense": ['branch', 'amount'],
    "branch_gma": ['branch', 'count'],
    "branch_growth_trend": ['month', 'count'],
    "branch_revenue": ['branch_name', 'date', 'revenue'],
    "branch_sales": ['branch', 'amount'],
    "branch_stock": ['branch_id', 'branch_name', 'product_name', 'category', 'assets_qty', 'consumable_qty', 'resell_qty', 'in_transit_qty', 'reserved_qty', 'status'],
    "branch_stock_chart": ['branch_id', 'total_stock'],
    "branch_type_distribution": ['branch_type', 'count'],
    "central_stock_entries": ['entry_id', 'product_name', 'supplier_name', 'invoice_number', 'invoice_date', 'total_qty', 'assets_qty', 'consumable_qty', 'resell_qty', 'total_with_tax', 'created_at'],
    "chemical_consumption": ['product_name', 'total_consumption'],
    "compensation_audit": ['emp_id', 'name', 'department', 'salary_type', 'basic', 'hra', 'deductions'],
    "contract_status_split": ['has_contract', 'count'],
    "country_revenue": ['date', 'revenue'],
    "critical_expiry": ['quotation_number', 'valid_till'],
    "critical_hiring": ['id', 'department', 'designation', 'positions', 'expected_joining'],
    "customer_revenue": ['customer_id', 'customer_name', 'total_revenue'],
    "customer_type": ['type', 'count'],
    "daily_po": ['date', 'count'],
    "daily_tickets": ['date', 'count'],
    "delayed_joining": ['id', 'department', 'designation', 'expected_joining', 'status'],
    "employee_growth": ['date', 'count'],
    "employee_list": ['employee_name', 'email', 'phone', 'role', 'status', 'created_at', 'branch'],
    "employees_by_department_type": ['department', 'employment_type', 'count'],
    "employees_by_role": ['role', 'count'],
    "employment_type": ['type', 'count'],
    "expired_consumables": ['product_name', 'expiry_date'],
    "expiring_contract_alerts": ['id', 'vendor_name', 'contract_end_date'],
    "expiring_contracts": ['contract_id', 'customer_name', 'value', 'end', 'status', 'branch'],
    "expiring_quotes": ['quotation_number', 'valid_till', 'amount', 'created_by'],
    "expiry_alert": ['contract_id', 'customer_name', 'end_date', 'value', 'status'],
    "high_amount": ['id', 'category', 'amount', 'status', 'submitted_at'],
    "high_in_transit_stock": ['product_name', 'in_transit_qty'],
    "high_leave": ['employee', 'leave_count'],
    "high_priority_alert": ['ticket_number', 'issue_type', 'priority', 'status', 'created_at'],
    "high_reserved_stock": ['product_name', 'reserved_qty'],
    "high_value": ['po_number', 'amount'],
    "high_value_orders": ['so_number', 'customer_id', 'amount', 'status', 'created_at'],
    "high_value_pending": ['quotation_number', 'amount'],
    "high_value_quotes": ['quotation_number', 'source', 'amount', 'status', 'created_at'],
    "hiring_pipeline": ['status', 'count'],
    "inactive_branch_alerts": ['branch_name', 'branch_code', 'status'],
    "inactive_customers": ['customer_id', 'name', 'type', 'branch_id', 'status'],
    "invalid_branch_code_alerts": ['branch_name', 'branch_code'],
    "inventory_value_by_category": ['category', 'value'],
    "invoice_details": ['invoice_number', 'customer_id', 'customer_name', 'invoice_date', 'grand_total', 'status'],
    "invoice_status": ['status', 'count'],
    "late_delivery": ['po_number', 'delivery_date'],
    "low_leave_balance": ['user_id', 'casual_leave', 'sick_leave'],
    "low_stock_alerts": ['product_name', 'branch_id'],
    "low_stock_products": ['product_name', 'product_code', 'branch_id', 'branch_name', 'category', 'assets_qty', 'consumable_qty', 'resell_qty', 'status'],
    "low_vendor_rating_alerts": ['id', 'vendor_name', 'vendor_rating'],
    "material_usage": ['task_number', 'product', 'uom', 'required_qty', 'used_qty', 'scheduled_date'],
    "monthly": ['month', 'value'],
    "monthly_contract_revenue": ['month', 'total_revenue'],
    "monthly_gma": ['month', 'count'],
    "monthly_gma_value": ['month', 'total_cost', 'total_price', 'avg_margin'],
    "monthly_purchase_value": ['month', 'total'],
    "monthly_requests": ['date', 'count'],
    "monthly_revenue": ['month', 'revenue'],
    "monthly_stock_comparison": ['month', 'assets', 'consumables', 'resell'],
    "monthly_trend": ['month', 'count'],
    "monthly_value": ['month', 'value'],
    "no_contract_customers": ['customer_id', 'name', 'type', 'created_at'],
    "no_sales_order": ['contract_id', 'value', 'start_date', 'status'],
    "old_open_tickets": ['ticket_number', 'priority', 'status', 'created_at'],
    "onboarding_trend": ['date', 'count'],
    "open_high_priority": ['ticket_number', 'customer', 'issue_type', 'priority', 'status', 'created_at'],
    "out_of_stock_alerts": ['product_name'],
    "out_of_stock_products": ['product_name', 'product_code', 'branch_id', 'branch_name', 'category'],
    "overdue_tasks": ['task_number', 'customer_id', 'service', 'scheduled_date', 'status'],
    "pending_alert": ['id', 'source_type', 'status', 'deadline', 'created_at'],
    "pending_old": ['id', 'category', 'amount', 'status', 'submitted_at'],
    "pending_orders": ['so_number', 'customer_id', 'status', 'created_at'],
    "po_status": ['status', 'count'],
    "priority_chart": ['priority', 'count'],
    "product_consumption": ['product_code', 'product_name', 'consumable_qty'],
    "rating_distribution": ['vendor_rating', 'count'],
    "recent_branch_activations": ['branch_name', 'branch_code', 'branch_type', 'created_at', 'created_by'],
    "recent_contracts": ['contract_id', 'customer_name', 'gma_id', 'value', 'start', 'end', 'status', 'branch'],
    "recent_customers": ['customer_id', 'name', 'type', 'phone', 'branch', 'status', 'created_at'],
    "recent_gma": ['id', 'source_type', 'contract_duration', 'proposed_start_date', 'branch_name', 'total_annual_price', 'status', 'created_at'],
    "recent_orders": ['so_number', 'customer_name', 'order_type', 'amount', 'status', 'branch', 'created_at'],
    "recent_po": ['po_number', 'vendor', 'po_date', 'delivery_date', 'amount', 'status', 'branch'],
    "recent_requests": ['request_id', 'employee', 'branch', 'category', 'requested_amount', 'approved_amount', 'status', 'submitted_at'],
    "recent_stock_movements": ['reference_type', 'reference_id', 'product_id', 'product_name', 'branch_id', 'branch_name', 'stock_type', 'quantity_delta', 'action', 'created_by', 'created_at'],
    "recent_tasks": ['task_number', 'customer', 'so_number', 'service', 'scheduled_date', 'start_time', 'end_time', 'status'],
    "recent_tickets": ['ticket_number', 'customer', 'issue_type', 'priority', 'status', 'created_at', 'branch'],
    "recent_vendor_additions": ['id', 'vendor_name', 'vendor_type', 'created_at', 'vendor_status'],
    "revenue_breakup": ['type', 'value'],
    "revenue_summary": ['branch_id', 'branch_name', 'total_revenue'],
    "salary_slips": ['employee_name', 'year', 'month', 'basic_salary', 'net_salary', 'payment_date'],
    "salary_trend": ['year', 'month', 'salary'],
    "sales_order_items": ['so_number', 'customer_name', 'product_name', 'quantity', 'uom', 'unit_price', 'tax_amount', 'line_total'],
    "source": ['source', 'count'],
    "state_distribution": ['state', 'count'],
    "status": ['status', 'count'],
    "status_breakdown": ['status', 'count'],
    "status_chart": ['status', 'count'],
    "status_distribution": ['status', 'count'],
    "stock_by_category": ['category', 'total_stock'],
    "stock_movement_trend": ['date', 'movement'],
    "stock_transfers": ['product_name', 'assets_qty', 'consumable_qty', 'resell_qty', 'source_branch_id', 'branch_name'],
    "task_summary": ['status', 'total_tasks'],
    "technician_overload": ['technician', 'date', 'task_count'],
    "technician_productivity": ['technician_id', 'technician_name', 'total_tasks', 'total_revenue', 'productivity'],
    "technician_workload": ['technician', 'count'],
    "unpaid_salary": ['employee', 'year', 'month', 'salary'],
    "vendor_outstanding": ['vendor_name', 'paid_amount', 'pending_amount', 'grand_total'],
    "vendor_spending": ['vendor', 'amount'],
    "vendor_summary": ['vendor', 'branch', 'total_orders', 'total_amount', 'last_purchase'],
    "vendors_by_category": ['vendor_category', 'count'],
}
